FromDoppler/doppler-style-guide

- src/assets/scss/modules/_dropdown.scss
- src/doc/templates/buttons-component.html
- menu styling settings for the webapp
> fix: changing anchor elements by button for the editors menu

- src/assets/scss/modules/_dropdown.scss
- src/doc/templates/buttons-component.html
> fix: add support for buttons and links in menu editors

- package.json
- src/index.js
- src/util.js
- webpack-common.config.js
- webpack-prod.config.js
- webpack.config.js
- yarn.lock
Se actualizaron los script para la construcción del manifestó y los entrypoints
> WIP: [DE-520] Agregado folder JS a la compilación con webpack

- src/assets/scss/modules/_buttons.scss
- src/assets/scss/modules/_dropdown.scss
- src/documentation/templates/buttons-component.html
> fix: fix menu editor

- src/assets/scss/modules/_breakpoints.scss
- src/assets/scss/templates/_header.scss
> fix: fix menu responsive

- src/documentation/js/dropdown.js
- src/documentation/js/index.js
Para mejorar la consistencia de los script queremos que estos se ejecuten cuando el documento este listo para usar, nos apoyamos en el método onReady de Jquery para lograr.
> [DE-577] Refactorización del script legado

- src/assets/scss/modules/_forms.scss
> fix: resolve form validation

- src/assets/scss/modules/_forms.scss
> Resolve intl phone input display

- src/assets/scss/modules/_tooltip.scss
> Solve visualization of the graph of days weeks hours

- src/assets/scss/helpers/_colors.scss
- src/assets/scss/modules/_ribbons.scss
- src/assets/scss/styles.scss
> fix: add style for ribbons

- src/documentation/templates/partials/_head.html
Related to https://github.com/FromDoppler/mfe-loader/pull/13
> DE-666 - Update MFE loader

- src/assets/scss/core/_typography.scss
- src/assets/scss/templates/_dashboard.scss
- src/documentation/templates/dashboard.html
> feat: create stepper component for dashboard

- src/assets/scss/templates/_dashboard.scss
- src/documentation/templates/dashboard.html
> feat: modification dashboard of my campaigns my contacts

- src/assets/scss/templates/_doppler-plus.scss
- src/assets/scss/templates/_header.scss
> DE-777 fix menu mfe

- src/assets/scss/modules/_atomic-class.scss
- src/assets/scss/modules/_backgrounds.scss
- src/assets/scss/templates/_confirmation.scss
- src/documentation/templates/confirmation-page.html
- Removing background blocks
- Removal of unnecessary styles for blocks
- Semantic restructuring of html
- Elimination of unnecessary sizes
> Fix signup confirmation

- src/assets/scss/templates/_reportes.scss
> feat: change gray and arrow headers to white background

- src/assets/scss/templates/_header.scss
Related to: [DE-793](https://makingsense.atlassian.net/browse/DE-793)
> [DE-793] fix: broken sub menu

- src/assets/scss/templates/_reportes.scss
Add hero banner center for doppler in text align center header cases
> feat: add hero banner text center for doppler

- src/assets/scss/templates/_doppler-plus.scss
- src/documentation/templates/buttons-component.html
- src/documentation/templates/plan-calculator.html
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1155
**Before:** 
**After:**
> feat: add marks to slider

- src/assets/scss/templates/_doppler-plus.scss
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1195
**More Details** https://makingsense.slack.com/archives/CRXR62TC2/p1665760882856509
**Before**
**After:**
> fix: fix click in slider

- src/documentation/templates/integrations.html
> feat: add header in shopify page

- src/assets/scss/modules/_carousel.scss
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1206
**BEFORE**
- **Desktop**
- **Mobile**
- shorter text
longer text
**AFTER**
- **Desktop**
- **Mobile**
- shorter text
longer text
> feat: change layout in Learn With Doppler carousel

- src/assets/scss/modules/_buttons.scss
**Add a class for when the button is disabled**
> fix: add classes to segments button

- src/assets/scss/helpers/_classes.scss
> fix: fix in create templates button

- src/assets/scss/helpers/_classes.scss
> fix: alignment of create campaign and link colors

- src/assets/scss/helpers/_classes.scss
> fix: color links in cancel and delete

- src/assets/scss/helpers/_classes.scss
> fix: incorrect focus display in Jquery selectBox plugin classes

- src/assets/scss/templates/_dashboard.scss
- src/documentation/templates/dashboard.html
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1247
**Figma:** https://www.figma.com/file/i3YPb187ChPFijkWJKxmUi/Dashboard?node-id=2748%3A11774&t=7QWwuenm4cNT0Cxw-0
**Result:**
> feat: add quick actions

- src/assets/scss/helpers/_classes.scss
> fix: align icons in table

- src/assets/scss/modules/_forms.scss
- src/assets/scss/templates/_signup.scss
- src/documentation/templates/signup.html
Add new font size for accessibility and override auto zoom
https://user-images.githubusercontent.com/46735526/208909984-8e7aac41-7301-4a82-a68a-33797f44bdf2.MP4
https://user-images.githubusercontent.com/46735526/208910005-b25622e2-0c04-4a28-97f9-0362614174b3.MP4
> fix: add new font size for accessibility and override auto zoom

- src/assets/scss/templates/_header.scss
> fix: fix color icons for beamer notifications

- src/assets/scss/templates/_header.scss
> fix: icon notifications

- src/assets/scss/helpers/_classes.scss
- src/assets/scss/modules/_tables.scss
> Fix in layout list classes

- src/assets/scss/helpers/_classes.scss
> fix: fix grey panel box

- src/assets/scss/helpers/_classes.scss
> fix: color link doppler tip

- src/assets/scss/modules/_forms.scss
> fix: change button to 100 in mobile

- src/assets/scss/helpers/_animations.scss
- src/stories/Animations.js
- src/stories/Animations.stories.js
Pulse animation - Storibook [Documentation](https://cdn.fromdoppler.com/doppler-style-guide/documentation/pr-225/storybook/?path=/story/components-animations--default)
https://user-images.githubusercontent.com/6733401/221240816-e6f0c123-547e-4c46-9ab2-c3193f572b3a.mp4
> [DE-808] Add pulse animation

- src/assets/scss/modules/_inputs.scss
- src/documentation/templates/component-inputs.html
- src/stories/Inputs.email.js
- src/stories/Inputs.email.stories.js
- src/stories/Inputs.phone.js
- src/stories/Inputs.phone.stories.js
- src/stories/Inputs.text.js
- add story to storybook
To see:
https://cdn.fromdoppler.com/doppler-style-guide/documentation/pr-236/storybook/?path=/story/components-inputs-email--default
To check old forms:
https://cdn.fromdoppler.com/doppler-style-guide/documentation/pr-236/doppler-plus-plans-form.html
https://cdn.fromdoppler.com/doppler-style-guide/documentation/pr-236/signup.html
https://cdn.fromdoppler.com/doppler-style-guide/documentation/pr-236/login.html
> feat: creation of component input email and input phone

- src/assets/scss/core/_settings.scss
- src/assets/scss/modules/_tooltip.scss
- src/assets/scss/templates/_header.scss
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1409
**Fix this: tooltip overlay**
> Dat 1409 fix beamer tooltip

- src/assets/scss/templates/_payment-process.scss
- src/documentation/templates/payment-process.html
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1419
**NOTE:** ⚠️⚠️ don't merge yet ⚠️⚠️
**Before**
**After**
> feat: change secure payment && buy buttons

- src/assets/scss/templates/_payment-process.scss
- src/documentation/templates/payment-process.html
Reverts FromDoppler/doppler-style-guide#252
> Revert "feat: change secure payment && buy buttons"

- src/assets/scss/helpers/_classes.scss
> fix: change color button excel in doppler

- src/assets/scss/helpers/_classes.scss
> fix: align content in campaigns scheduled

- src/assets/scss/templates/_header.scss
> fix: remove space

- src/assets/scss/templates/_payment-process.scss
- src/documentation/templates/payment-process.html
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1475
**Figma:** https://www.figma.com/file/9G0dHcLds8b1LkwP1Tbwf0/Proceso-de-compra?node-id=10371-22987&t=0kFpDM20G5mYc88N-0
**BEFORE:**
**AFTER:**
> Dat 1475 add new invoice recipients in billing information

- src/assets/scss/templates/_payment-process.scss
- src/documentation/templates/payment-process.html
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1418
**Figma:** https://www.figma.com/file/9G0dHcLds8b1LkwP1Tbwf0/Proceso-de-compra?type=design&node-id=10371-22987&t=i2x5R9TzyM6dqJMa-0
**Important:** the class `dp-steps-payment-process` should be applied when step is active.
> feat: add container to save button

- src/assets/scss/helpers/_classes.scss
> fix: remove paddings and margins

- src/assets/scss/templates/_header.scss
- src/documentation/templates/header-component.html
- src/js/index.js
The two coexist simultaneously
**Menu new**
[CDN link](https://cdn.fromdoppler.com/doppler-style-guide/documentation/pr-293/header-component.html)
> feat: create new submenu

- src/assets/scss/modules/_inputs.scss
- src/documentation/templates/component-inputs.html
- src/stories/Inputs.file.js
- src/stories/Inputs.file.stories.js
[Link Preview in Storybook](https://cdn.fromdoppler.com/doppler-style-guide/documentation/pr-298/storybook/?path=/story/components-inputs-file--default)
> feat: create input file component

- src/assets/scss/helpers/_classes.scss
- src/assets/scss/modules/_modal.scss
Related to https://github.com/FromDoppler/doppler-editors-webapp/pull/578
> Add styles for Unlayer editor custom media gallery

- src/assets/scss/helpers/_classes.scss
https://github.com/FromDoppler/doppler-style-guide/assets/1157864/644e562d-53ba-4c0d-8b04-b3fee325f203
> DOP-1366 - Fix custom media gallery layout

- src/assets/scss/modules/_inputs.scss
> fix: show eyed icon

- src/assets/scss/modules/_messages.scss
- src/documentation/templates/messages-component.html
> Dat 1565 gallery messages for user in unlayer

- src/assets/scss/modules/_inputs.scss
- src/documentation/templates/component-inputs.html
- src/stories/Inputs.phone.js
> fix: add padding left for tel

- src/assets/scss/helpers/_colors.scss
- src/assets/scss/modules/_buttons.scss
- src/assets/scss/modules/_modal.scss
It adds to the Style Guide some customizations that we need for the Custom Media Gallery.
> Gallery modals UI

- src/assets/scss/modules/_modal.scss
> Add new modal mod for error messages

- src/assets/scss/modules/_breadcrumb.scss
- src/documentation/templates/breadcrumb-component.html
- src/stories/new.breadcrumb.js
[Link Storybook](https://cdn.fromdoppler.com/doppler-style-guide/documentation/pr-355/storybook/?path=/story/components-new-breadcrumb--default)
> fix: fix arrow in breadcrumb component

- src/assets/scss/modules/_forms.scss
- src/documentation/templates/component-elements-checked.html
- src/stories/Input.radio.checkout.js
[Link Storybook](https://cdn.fromdoppler.com/doppler-style-guide/documentation/pr-357/storybook/?path=/story/components-input-radio-checkout--default)
> fix: add disabled state for radio component

- src/assets/scss/templates/_doppler-plus.scss
- src/documentation/templates/buttons-component.html
- src/stories/Slider.II.js
- src/stories/Slider.II.stories.js
> Dat 1602 new slide component

- src/assets/scss/helpers/_colors.scss
- src/assets/scss/modules/_buttons.scss
- src/documentation/templates/buttons-component.html
- src/stories/Button.Tertiary.js
- src/stories/Button.Tertiary.stories.js
[Link Storybook -->](https://cdn.fromdoppler.com/doppler-style-guide/documentation/pr-364/storybook/?path=/story/components-button-tertiary--default&globals=backgrounds.value:!hex(F8F8F8))
> feat: create new button tertiary

- src/assets/scss/modules/_buttons.scss
- src/assets/scss/modules/_dropdown.scss
- src/documentation/templates/buttons-component.html
- src/js/index.js
- src/stories/Button.Dropdown.js
- src/stories/Button.Dropdown.stories.js
[Link Storybook -->](https://cdn.fromdoppler.com/doppler-style-guide/documentation/pr-366/storybook/?path=/story/components-button-dropdown--default&args=disabled:true)
> fix: fix colors in button dropdown

- src/assets/scss/modules/_tabs.scss
- src/assets/scss/templates/_doppler-plus.scss
> fix: fix in tabs plans

- src/assets/scss/modules/_forms.scss
- src/documentation/templates/contact-policy.html
- src/stories/Contact.Policy.js
- src/stories/Contact.Policy.stories.js
> fix: fix in message error inputs in contact policy

- src/assets/scss/templates/_doppler-plus.scss
- src/documentation/templates/types-of-plans.html
- src/stories/Types.Of.Plans.js
> fix: change link for title transfer

- src/assets/scss/modules/_card.scss
- src/documentation/templates/types-of-plans.html
- src/stories/Types.Of.Plans.js
[Link Storybook -->](https://cdn.fromdoppler.com/doppler-style-guide/documentation/pr-380/storybook/?path=/story/components-types-of-plans--default)
> fix: change of paddings on cards

- src/assets/scss/modules/_forms.scss
- src/documentation/templates/component-elements-checked.html
- src/stories/Input.radio.checkout.js
[### Link Storybook -->
](https://cdn.fromdoppler.com/doppler-style-guide/documentation/pr-386/storybook/?path=/story/components-input-radio-checkout--default)
> feat: show tooltip information in plans

- src/assets/scss/templates/_doppler-plus.scss
- src/assets/scss/templates/_payment-process.scss
- src/documentation/templates/payment-process.html
- src/stories/Shopping.Card.js
> fix: remove promocode

- src/assets/scss/templates/_payment-process.scss
- src/documentation/templates/payment-process.html
> fix: item payment method in form

- src/assets/scss/templates/_payment-process.scss
- src/documentation/templates/payment-process.html
- src/stories/Shopping.Card.js
[Storybook --> ](https://cdn.fromdoppler.com/doppler-style-guide/documentation/pr-393/storybook/?path=/story/components-shopping-card--default)
> feat: add new component payment method

- src/assets/scss/templates/_doppler-plus.scss
- src/documentation/templates/types-of-plans.html
> fix: add logo change bank transfer

- src/assets/scss/templates/_list-selection.scss
> fix: in list check

- src/assets/scss/helpers/_classes.scss
> fix: fix layout edit segment

- src/assets/scss/templates/_payment-process.scss
- src/documentation/templates/types-of-plans.html
- src/stories/Titles.selection.plans.js
- src/stories/Titles.selection.plans.stories.js
[Link Storybook -->](https://cdn.fromdoppler.com/doppler-style-guide/documentation/pr-413/storybook/?path=/story/components-titles-selection-plans--default)
> feat: add titles icons for purchasing plans

- src/assets/scss/templates/_reportes.scss
> feat: add new style for concept chat

- src/assets/scss/templates/_payment-process.scss
- src/documentation/templates/checkout-success.html
- src/stories/Summary.js
- src/stories/Summary.stories.js
> feat: new layout summary

- src/assets/scss/templates/_dashboard.scss
- src/documentation/templates/dashboard.html
> fix: icons in dashboard

- src/assets/scss/templates/_payment-process.scss
- src/documentation/templates/payment-process.html
- src/stories/Shopping.Card.js
[Link Storybook -->](https://cdn.fromdoppler.com/doppler-style-guide/documentation/pr-427/storybook/?path=/story/components-shopping-card--default)
> fix: add next bills component

- src/assets/scss/templates/_payment-process.scss
- src/documentation/templates/payment-process.html
> fix: fix in payment process

- src/assets/scss/modules/_pagination.scss
- src/documentation/templates/plan-chat.html
- src/stories/Steper.js
- src/stories/Steper.stories.js
[Link Storybook -->](https://cdn.fromdoppler.com/doppler-style-guide/documentation/pr-448/storybook/?path=/story/components-steper--default)
> feat: add new component steper

- src/assets/scss/modules/_card.scss
- src/documentation/templates/types-of-plans.html
> fix: add discount types plans for arg

- src/assets/scss/templates/_payment-process.scss
- src/documentation/templates/payment-process.html
- src/stories/Shopping.Card.js
[Link Storybook -->](https://cdn.fromdoppler.com/doppler-style-guide/documentation/pr-464/storybook/?path=/story/components-shopping-card--default)
> fix: add color discount arg

- src/assets/scss/templates/_reportes.scss
> fix: fix in content

- src/assets/scss/helpers/_colors.scss
- src/assets/scss/templates/_payment-process.scss
> fix: change color label discount arg

- src/assets/scss/templates/_reportes.scss
> fix: fix in text elements chat

- src/assets/scss/modules/_forms.scss
- src/documentation/templates/dashboard.html
- src/stories/Box.packs.js
- src/stories/Box.packs.stories.js
[Pack Landings Storybook link -->](https://cdn.fromdoppler.com/doppler-style-guide/documentation/pr-488/storybook/?path=/story/components-box-packs--default)
State:
- Default
- Disabled
- Error
> feat: add pack the landings

- src/assets/scss/modules/_card.scss
- src/documentation/templates/payment-process.html
- src/stories/Addons.Card.js
- src/stories/Addons.Card.stories.js
[Link Storybook -->](https://cdn.fromdoppler.com/doppler-style-guide/documentation/pr-490/storybook/?path=/story/components-addons-card--default)
> feat: add new component addons card

- src/assets/scss/templates/_payment-process.scss
- src/documentation/templates/payment-process.html
> fix: Add disabled status for all payment frequencies

- src/assets/scss/templates/_header.scss
- src/documentation/templates/nav-user-component.html
> fix: add alt text for user menu

- src/assets/scss/modules/_tabs.scss
- src/documentation/templates/dashboard.html
- src/stories/My.Plans.js
- src/stories/My.Plans.stories.js
[Link Storybook -->](https://cdn.fromdoppler.com/doppler-style-guide/documentation/pr-513/storybook/?path=/story/components-my-plans--default)
> feat: add new page my plan layout

- src/assets/scss/modules/_buttons.scss
- src/assets/scss/templates/_dashboard.scss
- src/documentation/templates/dashboard.html
- src/stories/My.Plans.js
[Link Storybook -->](https://cdn.fromdoppler.com/doppler-style-guide/documentation/pr-514/storybook/?path=/story/components-my-plans--default)
> feat: add new plans

- src/assets/scss/templates/_dashboard.scss
- src/documentation/templates/dashboard.html
- src/stories/My.Plans.js
[Link Storybook -->](https://cdn.fromdoppler.com/doppler-style-guide/documentation/pr-517/storybook/?path=/story/components-my-plans--default)
> feat: add component addons

- src/assets/scss/modules/_card.scss
- src/documentation/templates/dashboard.html
- src/stories/My.Plans.js
[Link Storybook -->](https://cdn.fromdoppler.com/doppler-style-guide/documentation/pr-522/storybook/?path=/story/components-my-plans--default)
> feat: add new card for my plan

- src/assets/scss/modules/_modal.scss
- src/documentation/templates/dashboard.html
- src/js/index.js
- src/stories/My.Plans.js
[Link Storybook -->](https://cdn.fromdoppler.com/doppler-style-guide/documentation/pr-526/storybook/?path=/story/components-my-plans--default)
> feat: add new modal unsubscriber in my plan

- src/assets/scss/modules/_modal.scss
- src/documentation/templates/dashboard.html
- src/js/index.js
> feat: add new modal discount code confirmation

- src/assets/scss/modules/_pagination.scss
> fix: fix in stepper spacing

- src/assets/scss/helpers/_icons-glyph-smooth.scss
- src/documentation/templates/icons-components.html
> fix: change class name to avoid conflict

- src/assets/scss/modules/_modal.scss
- src/assets/scss/templates/_header.scss
- src/documentation/templates/nav-user-component.html
- src/documentation/templates/subscriber-history.html
> feat: add new button in user menu

- src/assets/scss/modules/_carousel.scss
- src/assets/scss/modules/_modal.scss
- src/documentation/templates/dashboard.html
> fix: add carousel in modal

- src/stories/Tabs.js
- src/stories/Tabs.stories.js
> fix: add tabs component in storybook

- src/stories/Addons.Card.js
- src/stories/Addons.Card.stories.js
- src/stories/Box.packs.js
- src/stories/Box.packs.stories.js
- src/stories/Carousel.js
- src/stories/Carousel.stories.js
- src/stories/Contact.Policy.js
- src/stories/Contact.Policy.stories.js
- src/stories/Messages.for.user.js
- src/stories/Steper.js
- src/stories/Steper.stories.js
- src/stories/Tabs.js
- src/stories/Tabs.stories.js
> fix: add carousel component in storybook

- src/assets/scss/modules/_modal.scss
- src/assets/scss/templates/_list-selection.scss
- src/documentation/templates/modal-component.html
- src/js/index.js
Add transparent modal for videos
Also make clickable the img:
> [DOI-1576] Promotional video modal

- src/js/charts.js
chore: remove unused console log
> Remove unused console

- src/documentation/templates/onsite-dashboard.html
- src/index.js
- src/js/charts.js
- yarn.lock
Se agregó el componente BarChart al template onsite-dashboard, no fue necesario agregar nuevos estilos, los cambios se manejaron dentro de las opciones del mismo componente.
> Dph #59 bar chart styles

- src/assets/scss/modules/_index.scss
- src/assets/scss/modules/_ribbons.scss
- src/assets/scss/modules/_widget-card.scss
- src/stories/Widget.Card.js
- src/stories/Widget.Card.stories.js
- Add dp-widget-card class and styles
- Add Widget-Card story
> Dph #74 widgets cards styles

- src/assets/scss/modules/_dropdown.scss
- src/assets/scss/modules/_tables.scss
- src/assets/scss/modules/_widget-card.scss
- src/stories/Widget.Card.js
- src/stories/Widget.Info.Card.js
- src/stories/Widget.Info.Card.stories.js
> Dph #87 widget card info styles

- src/assets/scss/modules/_ribbons.scss
> Dph #92 fix widget card styles

- src/assets/scss/modules/_modal.scss
- src/assets/scss/modules/_widget-card.scss
- src/stories/Widget.Info.Card.js
- Update Modal styles 
- Update Widget Info Card styles
> Dph #178 delete widget modal

- src/assets/scss/core/_typography.scss
- src/assets/scss/modules/_footer.scss
- src/assets/scss/modules/_index.scss
- src/assets/scss/modules/_widget-card.scss
- webpack-common.config.js
> FOP-1716 - Add onsite footer style

- src/assets/scss/modules/_card.scss
Add new class for the onsite card
**Before:**
**After:**
> [no-task] - Add new class for the onsite card

- src/assets/scss/modules/_widget-card.scss
Colores necesarios para la implementación de la progress bar.
> Color rojo para la barra de progreso

- src/stories/Widget.Plan.Progress.js
Se agrega margen superior e inferior a la barra de progreso.
> chore: add margin and bottom

- src/assets/scss/modules/_forms.scss
Se agregan unas clases nuevas para los estilos del datepicker
> Classes for date input

- src/assets/scss/modules/_modal.scss
Task: [DAT-2280](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2280)
[DAT-2280]: https://makingsense.atlassian.net/browse/DAT-2280?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DAT-2280]

- src/assets/scss/modules/_modal.scss
Set custom value for the z-index
> [no-task] - Set custom value for the z-index

- src/assets/scss/modules/_card.scss
Update style to include push notification icon
**Task:** [DAT-2432](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2432)
[DAT-2432]: https://makingsense.atlassian.net/browse/DAT-2432?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DAT-2432] - Update style to include push notification icon

- src/assets/scss/templates/_dashboard.scss
update style for the price section
> update style for the price section

- src/assets/scss/templates/_dashboard.scss
Update styles
**Task:** [DAT-2568](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2568)
[DAT-2568]: https://makingsense.atlassian.net/browse/DAT-2568?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DAT-2568] - Update styles

- src/assets/scss/modules/_modal.scss
> [no-task] - Add class for the new modal

- src/assets/scss/modules/_modal.scss
Add new class for the container buttons
> [no-task] - Add new class for the container buttons
