webpack.config.js

<s>Implementar `node-sass-glob-importer` en la configuración de webpack</s>
Se propone usar la forma de importar los archivos en las hojas de estilo como lo indica la documentación de [SASS](https://sass-lang.com/documentation/at-rules/use) con esto es innecesario el uso del plugin `node-sass-glob-importer` y de `node-sass DEPRECATED`
_**nota 1:**_ Luego de hacer una prueba de concepto usando [_@use_](https://sass-lang.com/documentation/at-rules/use) de _SASS_ se agregó en webpack la configuración de un alias para usar rutas relativas en los imports 👇 
`includePaths: [path.resolve(__dirname, "./src/assets/scss")],`
_**nota 2:**_ También se agregó una configuración para ubicar los _assets_ usados en la carpeta _/static/media_
[DE-467](https://makingsense.atlassian.net/browse/DE-467)

[DE-467] Configuración para assets

---

src/assets/scss/helpers/_classes.scss

Visibility hidden was added to the container so that the user cannot have action on the fields until the page is rendered

feat: add visibility hidden in overlay

---

src/assets/scss/modules/_grid-system.scss

Deprecation Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

fix: deprecation using / for division outside of calc

---

package.json
yarn.lock

Now, the dev script run the webpack dev server and storybook server in parallel.

[DE-709] Update dev script

---

src/assets/scss/modules/_tooltip.scss

fix: add max width in component tooltip block

---

src/assets/scss/helpers/_classes.scss

I need to use this mechanism without adding the `dp-library` class to the whole page.
I think that it will work without issues.
Thoughts?

fix: support "show after load" mechanism without dp-library container

---

.storybook/preview-head.html
src/documentation/templates/partials/_head.html
src/index.js
src/js/index.js

Hi team!
I am making this change to allow Style Guide clients to decide which behavior initialize and which does not.
I think that this will help us avoid issues like [DE-796](https://makingsense.atlassian.net/browse/DE-796) where Style Guide behavior conflicts with Menu MFE logic.

DE-796 - granuralize behavior initialization

---

src/assets/scss/helpers/_animations.scss
src/stories/Animations.js
src/stories/Animations.stories.js

Rename saving label.
<s>Refactor using [ARIA Live Regions](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions), the priority aria live is **_polite_**
> **aria-live:** The aria-live=_POLITENESS_SETTING_ is used to set the priority with which screen reader should treat updates to live regions - the possible settings are: off, polite or assertive. The default setting is off. This attribute is by far the most important.
</s>WON'T FIX
**_Issue related:_** [PR-431](https://github.com/FromDoppler/doppler-editors-webapp/pull/431)

[DE-808] Using region role in saving animation

---

src/assets/scss/templates/_payment-process.scss
src/documentation/templates/payment-process.html

**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1420
**Before:**
**After:**

feat: add zigzag to the end of purchase summary section

---

src/assets/scss/templates/_payment-process.scss
src/documentation/templates/payment-process.html

**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1428
**Before:**
**After:**

Dat 1428 changes styles in purchase summary section

---

src/assets/scss/core/_typography.scss
src/assets/scss/helpers/_colors.scss
src/assets/scss/templates/_header.scss
src/assets/scss/templates/_messages-header.scss
src/documentation/templates/header-component.html
src/stories/Header.js
src/stories/Header.stories.js

- add color variables
- add spacing variables
Figma: [mockup Header](https://www.figma.com/file/24sS51U589wMlAUmEntNyr/Navegaci%C3%B3n?node-id=126-2476&t=In76587pTvLNQEvS-0)
Storybook link: [Header Storybook](https://cdn.fromdoppler.com/doppler-style-guide/documentation/pr-262/storybook/?path=/story/components-header--default)

feat: create storybook template for user account header and messages

---

.storybook/preview-head.html
src/documentation/templates/partials/_head.html
src/index.js
src/js/index.js

UserMenu behavior is managed by React in Menu MFE, this javascript code conflicts with it and should not be enabled by default.
I did not remove the code because we need it to keep documentation demos working, it should be fixed in a future refactorization.

fix: do not init UserMenu behavior by default

---

.storybook/preview-head.html
src/documentation/templates/partials/_head.html
src/index.js
src/js/index.js
src/js/initFonts.js
src/stories/Header.js

Adding an optional configuration `window["style-guide-configuration"].initFonts`
When it is true, the _Style Guide_ will append `<link rel="stylesheet" href="https://use.typekit.net/fbq8dbp.css" />` into the `<head>` element loading _Proxima Nova_ font.
I am not sure if we should make it optional or always load this font. Thoughts?
See [documentation](https://cdn.fromdoppler.com/doppler-style-guide/documentation/pr-288) and [storybook](https://cdn.fromdoppler.com/doppler-style-guide/documentation/pr-288/storybook/).

Add configuration to load Proxima Nova font

---

src/assets/scss/modules/_inputs.scss
src/documentation/templates/component-inputs.html
src/stories/Inputs.file.js
src/stories/Inputs.file.stories.js

Cambie por completo el componente input file.
Anteriormente utilice los [data-attributes](https://developer.mozilla.org/es/docs/Learn/HTML/Howto/Use_data_attributes) para colocar mensajes de cara al usuario y manipularlos por CSS.
Si bien la fácil manipulación por CSS es una tentación, descubrí que **NO son accesibles** y el componente **pierde su semántica**, transformándose en una **mala practica** y en un componente inservible.
El nuevo componente presentado trabaja de forma nativa, perdemos un poco en diseño, pero nos queda un componente completamente accesible y semántico.
Dejo beneficios y contras por las dudas.
**Contras:**
- El diseño no queda tal cual el mockup
- No puedo manipular el mensaje del botón ni su placeholder, ya que el DOM toma por defecto el idioma y cada Browser …

fix: complete change of input file component for accessibility

---

src/assets/scss/modules/_inputs.scss
src/documentation/templates/component-inputs.html
src/stories/Inputs.password.js

[Link Storybook](https://cdn.fromdoppler.com/doppler-style-guide/documentation/pr-325/storybook/?path=/story/components-inputs-password--default)

fix: add validation input password

---

src/assets/scss/helpers/_classes.scss

It is not exactly the same checkbox, but it is pretty similar.

fix: improve image gallery checkbox

---

src/assets/scss/modules/_inputs.scss
src/documentation/templates/component-inputs.html
src/stories/Inputs.phone.js

To see in [Storybook](https://cdn.fromdoppler.com/doppler-style-guide/documentation/pr-348/storybook/?path=/story/components-inputs-phone--default)

fix: change type text to type number in input phone

---

src/assets/scss/modules/_buttons.scss
src/documentation/templates/buttons-component.html
src/stories/Switch.Button.js
src/stories/Switch.Button.stories.js

[Link Storybook -->](https://cdn.fromdoppler.com/doppler-style-guide/documentation/pr-381/storybook/?path=/story/components-switch-button--default)

fix: add new disabled state to switch buttons

---

src/assets/scss/modules/_messages.scss
src/stories/Messages.for.user.js
src/stories/Messages.for.user.stories.js

fix: fix font size in messages for users

---

src/stories/Types.Of.Plans.js

[Link Storybook ](https://cdn.fromdoppler.com/doppler-style-guide/documentation/pr-465/storybook/?path=/story/components-types-of-plans--default)

fix: change in storybook types of plans

---

src/assets/scss/modules/_widget-card.scss

There are some texts missing the right color. Now its like defined in the figma.
Also added a hover color for the link. I have to check that with the design team.

[DOI-1728] Add missing styles for widget hover card

---

src/assets/scss/modules/_inputs.scss
src/assets/scss/modules/_tooltip.scss

- Add `dp-tooltip-top-bubble` class to avoid class overlap on `.dp-tooltip-top > span` and  `input--radio label span`
- Add `dp-label-with-icon` class to properly align label text and icon

Dph #138 label with tooltip

---

src/assets/scss/modules/_tables.scss

Se agrega el color gris para usar para widgets inactivos y el red para widgets eliminados.

Grey and red color

---

src/assets/scss/modules/_widget-card.scss
src/stories/Widget.Plan.Progress.js
src/stories/Widget.Plan.Progress.stories.js

By controlling the components width we can show the progress. On reaching 100% we should add some custom classes that change the colors.

[DOI-1895] Add new component "widget plan progress bar"

---

src/assets/scss/modules/_forms.scss

Utilizando la posibilidad de extension que provee sass, cree una nueva clase que abarca los estilos de field-item y le suma el width que necesito para los fields de las rules de los widgets.

Extend field item for onsite rules

---

src/assets/scss/modules/_charts.scss
src/assets/scss/templates/_dashboard.scss

The KPI boxes will now automatically adjust to the container's width, with a maximum of six boxes displayed per row. Any boxes beyond that limit will wrap to a new line.
Furthermore, when the screen is resized, each box will maintain its minimum width. Instead of shrinking further, any boxes that no longer fit will move down to the row below.

[DOI-2326] Make KPIs responsive
